spring:
  application:
    name: mybatch
  batch:
    jdbc:
      initialize-schema: always
  #    job:
  #      enabled: true

  jpa:
    show-sql: true
    open-in-view: false
  #    hibernate:
  #      ddl-auto: none
  #    properties:
  #      hibernate:
  #        show_sql: true

  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      JdbcUrl: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver

    postgres:
      url: jdbc:postgresql://localhost:5432/mybash_db
      JdbcUrl: jdbc:postgresql://localhost:5432/mybash_db
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver